service: nibbly-backend

frameworkVersion: '2'

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1

  environment:
    tableName: nibbly-goats

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: 'arn:aws:dynamodb:ap-southeast-1:*:*'

functions:
  createGoat:
    handler: create.main
    events:
      - http:
          path: /goat
          method: post
          cors: true
          authorizer: aws_iam

  getGoat:
    handler: get.main
    events:
      - http:
          path: /goat/{goatId}
          method: get
          cors: true
          authorizer: aws_iam

  listGoats:
    handler: list.main
    events:
      - http:
          path: /goat
          method: get
          cors: true
          authorizer: aws_iam

  updateGoat:
    handler: update.main
    events:
      - http:
          path: /goat/{goatId}
          method: put
          cors: true
          authorizer: aws_iam

resources:
  Resources:
    GoatsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: goatId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: goatId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.tableName}
